name: PR Agent Open Source

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  pr_agent:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Run PR Agent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          config.model: "gemini/gemini-2.5-pro"
          config.fallback_models: '["gemini/gemini-2.5-flash"]'

          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
